name: Issue matching auto-closer
description: Automatically close issues based on regexs matching.
author: arkon
branding:
  icon: alert-circle
  color: red
inputs:
  issue-close-message:
    description: Message content to comment on the issue before closing
  issue-title-pattern:
    description: Regular expression pattern which the issue title if matched closes the issue
  issue-body-pattern:
    description: Regular expression pattern which the issue body if matched closes the issue
  repo-token:
    description: GitHub token
runs:
  using: node12
  main: dist/index.js
