name: Issue closer test
on: [issues]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Autoclose issue
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        rules: |
          [
            {
              "type": "title",
              "regex": ".*Test title.*",
              "message": "@${issue.user.login} this issue was automatically closed because the title was not updated."
            },
            {
              "type": "body",
              "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
              "message": "@${issue.user.login} this issue was automatically closed because the acknowledgment section was not removed."
            },
            {
              "type": "body",
              "regex": ".*Test: \\?.*",
              "message": "@${issue.user.login} this issue was automatically closed because the requested information was not filled out."
            }
          ]