name: Issue closer test
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Autoclose issue
      # uses: arkon/issue-closer-action@v2.0
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        rules: |
          [
            {
              "type": "title",
              "regex": ".*Test title.*",
              "message": "The title was not updated."
            },
            {
              "type": "body",
              "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
              "message": "The acknowledgment section was not removed."
            },
            {
              "type": "body",
              "regex": ".*Test: \\?.*",
              "message": "The requested information was not filled out."
            }
          ]